version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - DOCKER_IMAGE_NAME=leonardiwagner/cd:master
      - echo "Nodejs version"
      - node --version
      - echo "Docker version"
      - docker --version
  build:
    commands:
      - npm i
      - npm test
  post_build:
    commands:
      - echo pushing docker image $DOCKER_IMAGE_NAME
      - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - docker build -t $DOCKER_IMAGE_NAME .
      - docker push $DOCKER_IMAGE_NAME