version: 0.2
env:
  variables:
    DOCKER_IMAGE_NAME: leonardiwagner/cd:master
    AWS_CLUSTER_NAME: cdcluster
    AWS_SERVICE_NAME: cdservice
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo "Nodejs version:"
      - node --version
      - echo "Docker version:"
      - docker --version
  build:
    commands:
      - npm i
      - npm test
  post_build:
    commands:
      - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - docker build -t $DOCKER_IMAGE_NAME .
      - docker push $DOCKER_IMAGE_NAME
      - aws ecs update-service --force-new-deployment --service $AWS_SERVICE_NAME --cluster $AWS_CLUSTER_NAME --desired-count 1 --force-new-deployment  
