version: 0.2
env:
  variables:
    DOCKER_IMAGE_NAME: leonardiwagner/cd:latest
    AWS_CLUSTER_NAME: cdcluster
    AWS_SERVICE_NAME: cdservice2
    AWS_TASK_NAME: cd-task
    AWS_CODE_DEPLOY_APP: AppECS-cdcluster-cdservice2
    AWS_CODE_DEPLOY_GROUP: DgpECS-cdcluster-cdservice2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo "Nodejs version:"
      - node --version
      - echo "Docker version:"
      - docker --version
  build:
    commands:
      - npm i
      - npm test
  post_build:
    commands:
      - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - docker build -t $DOCKER_IMAGE_NAME .
      - docker push $DOCKER_IMAGE_NAME
      - aws ecs deploy
        --cluster $AWS_CLUSTER_NAME
        --service $AWS_SERVICE_NAME
        --codedeploy-application $AWS_CODE_DEPLOY_APP
        --codedeploy-deployment-group $AWS_CODE_DEPLOY_GROUP
        --task-definition ecs-task.json
        --codedeploy-appspec appspec.json
        
